name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connect EC2
        uses: appleboy/ssh-action@v1
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          envs: ENV
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/JpopX-server
            sudo git pull origin main
            sudo touch .env
            sudo echo "$ENV" > .env
            sudo pnpm i
            sudo pnpm run build
            sudo pm2 kill
            sudo pm2 start dist/main.js --name "server-running"