name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connect EC2
        uses: appleboy/ssh-action@v1
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          envs: ENV
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/JpopX-server
            
            # ENV 내용을 파일로 저장
            echo "$ENV" > /tmp/env_content
            
            # 파일 이동 및 권한 설정
            sudo git pull origin main
            sudo rm -f .env
            sudo cp /tmp/env_content .env
            sudo chown root:root .env
            sudo chmod 644 .env
            
            # 임시 파일 삭제
            rm -f /tmp/env_content
            
            sudo pnpm i
            sudo pnpm run build
            sudo pm2 kill
            sudo pm2 start dist/main.js --name "server-running"